canonical/data-platform-libs

- lib/charms/data_platform_libs/v0/data_interfaces.py
> fix relation broken

- lib/charms/data_platform_libs/v0/data_interfaces.py
- tests/unit/test_data_interfaces.py
> [MISC] is_resource_created method

- README.md
- lib/charms/data_platform_libs/v0/data_interfaces.py
> [ISSUE-45] Update documentation and data_interface library dependency

- metadata.yaml
To list charm on CharmHub we have to provide the list of basic requirements (definition of good).
> DPE-1180 Improve metadata.yaml to list on charmhub

- lib/charms/data_platform_libs/v0/upgrade.py
- pyproject.toml
- tests/unit/test_upgrade.py
- tox.ini
> docs: add full lib docstring

- .github/workflows/ci.yaml
- tests/integration/database-charm/src/charm.py
- tests/integration/test_charm.py
- tests/integration/test_kafka_charm.py
- tests/integration/test_opensearch_charm.py
- tests/integration/test_s3_charm.py
- tox.ini
Juju 3 matrix pipelines for data-platform-libs.
**NOTE**: Due to Juju bug [Inconsistent state in EnterScope](https://bugs.launchpad.net/juju/+bug/2031631) a workaround is also applied, making pipeline execution a bit more reliable.
> [DPE-2394] Juju3 pipeline

- lib/charms/data_platform_libs/v0/upgrade.py
- tests/unit/test_upgrade.py
Address issue #97 
* defer for vm only
* fix log message
Fix #97
> DPE-2660 VM specific defer

- .github/workflows/ci.yaml
- lib/charms/data_platform_libs/v0/data_interfaces.py
- tests/unit/test_data_interfaces.py
Currently no interface access is provided to retrieve data for the relation's "owner" (i.e. "this app") side.
This proposal is to fill that gap
> [DPE-2723] fetch_my_relation() data function

- lib/charms/data_platform_libs/v0/upgrade.py
> DPE-2751 - emit upgrade-granted for single units upgrades

- lib/charms/data_platform_libs/v0/data_interfaces.py
- tests/integration/database-charm/actions.yaml
- tests/integration/database-charm/src/charm.py
- tests/integration/helpers.py
- tests/integration/test_charm.py
NOTE: Code impacted by this fix is the very code delivering solution for Juju 3.1.7 (backwards compatible of course)
This code has been verified against `postgresql-operator`:
- Juju 3.1.6: https://github.com/canonical/postgresql-operator/pull/307
- Juju 3.1.7: https://github.com/canonical/postgresql-operator/pull/314
> Fixing DataPeerUnit major bug (issue #121)

- lib/charms/data_platform_libs/v0/data_interfaces.py
- tests/unit/test_data_interfaces.py
- [DPE-3332] secret usage for all interface calls
- issue https://github.com/canonical/data-platform-libs/issues/130
- [DPE-3312] Cosmetics on error message
- Issue #123 
[DPE-3332]: https://warthogs.atlassian.net/browse/DPE-3332?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DPE-3312]: https://warthogs.atlassian.net/browse/DPE-3312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DPE-3332][BUGFIX] secret usage for all interface calls

- lib/charms/data_platform_libs/v0/data_interfaces.py
- lib/charms/data_platform_libs/v0/database_provides.py
- lib/charms/data_platform_libs/v0/database_requires.py
- lib/charms/data_platform_libs/v0/s3.py
- lib/charms/data_platform_libs/v0/upgrade.py
Forgot to increase `LIBPATCH` in https://github.com/canonical/data-platform-libs/pull/131
Also, thanks to @MiaAltieri 's [PR](https://github.com/canonical/data-platform-libs/pull/133/files) from where I could "steal" the fix for the lint errors :-)
> [DPE-3356] LIBPATCH=27

- lib/charms/data_platform_libs/v0/upgrade.py
- tests/unit/test_upgrade.py
Testing rollback in VM charms, it often failed halting the event sequencing.
On inspection, it was possible to see concurrent `upgrade_granted` event being emitted on two units.
The solution seems to be removing a defer.
This is bit hard to pin down, but tests done on the [PR#401](https://github.com/canonical/mysql-operator/pull/401) of the mysql operator, indicates that the issue went away.
> Prevent concurrent upgrade_granted event emission

- .github/workflows/ci.yaml
- lib/charms/data_platform_libs/v0/data_interfaces.py
- tests/integration/database-charm/src/charm.py
- tests/integration/dummy-database-charm/src/charm.py
- tests/integration/test_charm.py
- tests/integration/test_rolling_upgrade.py
- tests/unit/test_data_interfaces.py
- https://github.com/canonical/data-platform-libs/issues/155
- https://github.com/canonical/data-platform-libs/issues/156
- https://github.com/canonical/data-platform-libs/issues/158
- https://github.com/canonical/data-platform-libs/issues/159
- https://github.com/canonical/data-platform-libs/issues/160
NOTE: Also testsed on 
- Postgres: https://github.com/canonical/pgbouncer-operator/pull/207
- MySQL: https://github.com/canonical/mysql-router-operator/pull/127 
- ignore the obvious "Check Libs" failure
- Zookeeper: https://github.com/canonical/zookeeper-operator/pull/129
> [DPE 4043] Bugixes for issues 155, 156, 158, 159, 160

- .github/workflows/ci.yaml
- lib/charms/data_platform_libs/v0/data_interfaces.py
- tests/integration/application-charm/metadata.yaml
- tests/integration/application-charm/src/charm.py
- tests/integration/test_kafka_charm.py
- Add the split pattern deployment to the tests on Kafka.
- Fix issue related to split pattern data access
> Add split pattern test

- lib/charms/data_platform_libs/v0/s3.py
Link to issue: https://warthogs.atlassian.net/browse/DPE-4401
Link to spec: https://docs.google.com/document/d/1WWMt_Q71cUIrpfYirp5TRCdkJXMjFSWCH6CTnKrO4YA/edit
See https://github.com/canonical/s3-integrator/pull/35 and https://github.com/canonical/postgresql-k8s-operator/pull/477
> [DPE-4401] add ability to backups be removed after a number of days

- lib/charms/data_platform_libs/v0/upgrade.py
- tests/unit/test_upgrade.py
The PostgreSQL VM charm rollback test started to fail by the combination of adding TimescaleDB to the Charmed PostgreSQL Snap + updating the `upgrade` library to LIBPATCH 16 (which removed a `defer` call that was hiding the issue fixed by this PR).
Explanation of the issue (considering the tests from the PostgreSQL VM charm):
* In the `test_upgrade_from_edge` test:
* TimescaleDB in the snap is leading to a longer snap refresh (only some more seconds).
* With that, Patroni is performing a failover, so a new unit, different from the Juju leader unit (the former primary), becomes the primary.
* Also with that, the former primary unit, the Juju leader unit, becomes a replica (not a synchronous standby).
* In the `test_fail_and_rollback` test:
* After the failed upgrade, the …
> [DPE-4598] Handle upgrade of top of the stack Juju leader

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- CONTRIBUTING.md
- lib/charms/data_platform_libs/v0/data_interfaces.py
- lib/charms/data_platform_libs/v0/data_models.py
- lib/charms/data_platform_libs/v0/data_secrets.py
- tests/unit/test_data_interfaces.py
- tox.ini
* Remove non-LTS Juju 3 test runs
* Update charming-actions action
* Update codespell and black linting drift
> [MISC] Use only  Juju 3.6 for tests

- lib/charms/data_platform_libs/v0/data_interfaces.py
- tests/integration/dummy-database-charm/lib/charms/data_platform_libs/v0/data_interfaces.py
Fix linting. Ruff drifted since the previous PR was opened.
> [DPE-6555] Fix linting

- lib/charms/data_platform_libs/v0/data_interfaces.py
This pull request includes several important changes to the `lib/charms/data_platform_libs/v0/data_interfaces.py` file, focusing on event handling and data management for the Etcd relation. The most significant changes involve the introduction of a new event, `EtcdReadyEvent`, and the addition of methods for setting URIs and TLS CA data.
Event handling updates:
* Replaced the `EtcdVersionUpdatedEvent` and `AuthenticationEvent` with a new `EtcdReadyEvent` to signal when the Etcd relation is ready. [[1]](diffhunk://#diff-7bc59790c534f66e8e6a800e826efade12b1320cfe3b37b4fdc9a41ca0b0a6dfL3891-R3892) [[2]](diffhunk://#diff-7bc59790c534f66e8e6a800e826efade12b1320cfe3b37b4fdc9a41ca0b0a6dfL3914-R3902) [[3]](diffhunk://#diff-7bc59790c534f66e8e6a800e826efade12b1320cfe3b37b4fdc9a41ca0b0a6dfL4091-R4097 …
> Add uris to etcd interface and change event name to etcd_ready

- tests/integration/application-s3-charm/charmcraft.yaml
- tests/integration/database-charm/charmcraft.yaml
- tests/integration/dummy-database-charm/charmcraft.yaml
- tests/integration/dummy-database-charm/lib/charms/data_platform_libs/v0/data_interfaces.py
- tests/integration/s3-charm/charmcraft.yaml
- tests/integration/secrets-charm/lib/charms/data_platform_libs/v0/data_secrets.py
This PR fixes the _lint_ and _integration_ CI steps by:
- Updating language to be codespell compliant.
- Including `opentelemetry-api` in the charmcraft binary package section for Ubuntu focal test charms.
---
Adding reviewers according to this Cross-team components maintainers [page](https://canonical-data.readthedocs-hosted.com/products/cross-team/).
> [MISC] Fix linting and integration tests

- lib/charms/data_platform_libs/v0/s3.py
Reduce the s3 logging. Porting changes from https://github.com/canonical/s3-integrator/pull/133 to the lib.
> [MISC] Reduce logging in s3 lib

- lib/charms/data_platform_libs/v0/data_interfaces.py
> [DPE-7709] Add Karapace interface
