- lib/charms/data_platform_libs/v0/database_provides.py
- tests/integration/application-charm/src/charm.py
- tests/integration/database-charm/src/charm.py
- tests/integration/helpers.py
- tests/integration/test_charm.py
- tests/unit/test_database_provides.py
In short this PR address JIRA ticket [DPE-418](https://warthogs.atlassian.net/browse/DPE-418).
In long:
* Database charms using the provides charm library should be able to handle multiple applications requesting new databases.
* Currently, the library can't handle this situation. It overrides the data from the first application in the relation databag because it's using the same relation without providing a relation id (the id that differentiates the connections being made to the same relation in the database charm).
* Use the relation id property from the relation linked to the custom events that are triggered inside the library.
* With the relation id it s possible to know which application is requesting the database and also send the credentials back.
* The documentation in the top of …
> Handle multiple applications connecting to the database

- lib/charms/data_platform_libs/v0/database_requires.py
- tests/integration/application-charm/src/charm.py
- tests/unit/test_database_requires.py
In short this PR partially address JIRA ticket [DPE-423](https://warthogs.atlassian.net/browse/DPE-423).
In long:
* Application charms using the requires charm library should be able to connect to multiple database clusters through the same relation.
* Currently, the library can't handle this situation. It faces some errors if we try to connect multiple clusters to the same relation because it doesn't provide a relation id (the id that differentiates the connections being made to the same relation in the database charm) when interacting with each different database cluster.
* Use the relation id property from the relation linked to the custom events that are triggered inside the library.
* With the relation id it's possible to know which database cluster the application is talking to at a …
> Add partial code to handle multiple clusters in the same relation

- tests/integration/application-charm/metadata.yaml
- tests/integration/application-charm/src/charm.py
- tests/integration/helpers.py
- tests/integration/test_charm.py
In short this PR address JIRA ticket [DPE-422](https://warthogs.atlassian.net/browse/DPE-422).
In long:
* Database charms using the requires charm library should be able to request multiple databases to the same database charm.
* Currently, this is something that isn't being tested.
* Add an integration test that ensures that the requires charm library can request multiple databases to the same database charm.
* Multiple relations are needed to accomplish that, because we can't relate twice the same application and database using the same relation name.
* Some updates were made in the `tests/integration/helpers.py`and `tests/integration/test_charm.py` files to handle .
* Unit tests were not updated on this PR as there wasn't any update in the libraries code.
* One more integration test …
> Update tester charm and add test for multiple databases requests

- lib/charms/data_platform_libs/v0/database_provides.py
- lib/charms/data_platform_libs/v0/database_requires.py
- lib/charms/harness_extensions/v0/capture_events.py
- tests/integration/test_charm.py
- tests/unit/test_database_provides.py
- tests/unit/test_database_requires.py
The emitter of DatabaseRequestedEvent don't set values to the event.unit nor event.app properties inherited from RelationEvent, so they are both defaulted to None https://github.com/canonical/data-platform-libs/issues/14.
The same applies to the requires side of the relation.
* Use the app and the unit from the original event in the function that emits the custom events.
* Skip `lib/charms/harness_extensions/v0/capture_events.py` when reviewing this PR (it is an imported library). For more details, check [this](https://discourse.charmhub.io/t/harness-recipe-capture-events/6581).
* Unit tests were updated and some new tests were implemented.
* Add app and unit information to custom events.
> Add app and unit information to events

- charmcraft.yaml
- pyproject.toml
- src/charm.py
- tox.ini
Add a simple placeholder charm (that was previously manually uploaded to charmhub to make available the pages showing the libraries).
> Add placeholder charm to enable libraries on Chamhub pages

- tests/integration/application-charm/metadata.yaml
- tests/integration/database-charm/metadata.yaml
- tests/unit/test_database_provides.py
- tests/unit/test_database_requires.py
Relation interface name must not include hyphens.
Change `-` to `_` in the relation interface names.
It is also being changed in this repository to not create confusion for people about how to name interfaces of relations when they start using the relation libraries.
* Rename relation interface names.
> Rename relation interface names

- .github/workflows/release.yaml
Update Charmhub action to 2.0.0-rc to avoid creating revisions named `revundefined`.
> Update Charmhub action

- lib/charms/data_platform_libs/v0/database_requires.py
Trivial change updating the docstring for the database requires side of the relation to mention that you also need to import the `DatabaseCreatedEvent` as it's referenced in the sample code below.
> Include DatabaseCreatedEvent in sample code

- .github/workflows/ci.yaml
Add the missing `workflow_call` trigger on `ci.yaml`. Without that, it's not possible to reuse the workflow on other workflows like `release.yaml`.
This need was reported on https://github.com/canonical/data-platform-libs/actions/runs/3249715434.
I missed that on https://github.com/canonical/data-platform-libs/pull/24 (Jira issue: [DPE-787](https://warthogs.atlassian.net/browse/DPE-787))
> Add missing workflow_call trigger to CI

- README.md
- lib/charms/data_platform_libs/v0/database_provides.py
- lib/charms/data_platform_libs/v0/database_requires.py
deprecate database_provides and database_requires libs in favor of data_interfaces
limit README.md line length to 99 chars
> DOCS: deprecate database_provides and database_requires libs

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
The new `release-libraries` action is introduces and should be used by default.
> Bump charming-actions to 2.2.0 + add release-libraries

- lib/charms/data_platform_libs/v0/database_provides.py
- lib/charms/data_platform_libs/v0/database_requires.py
Currently publishing is not possible:
> cd data-platform-libs.git && charmcraft publish-lib
> ...
> Library charms.data_platform_libs.v0.database_provides version 0.2 is the same than in Charmhub but content is different
> Library charms.data_platform_libs.v0.database_requires version 0.4 is the same than in Charmhub but content is different
> ...
Suspected commits f093eff04c5ead8ef80d2df35e609ac0eb062bed and 48e900386b3df0d40fdfb59e3d668b0f66d79457 (merged without bumping LIBPATCH).
> Bump database_provides/requires LIBPATCH version to fix publishing

- .github/workflows/release.yaml
At the moment, the current release-libraries@2.2.0 is failing with really strange error:
https://github.com/canonical/data-platform-libs/actions/runs/4067139974/jobs/7004849787
> Error: Not Found
> Error: HttpError: Not Found
>     at /home/runner/work/_actions/canonical/charming-actions/2.2.0/dist/release-libraries/index.js:8603:21
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
The version 2.2.1 has related fix:
https://github.com/canonical/charming-actions/releases/tag/2.2.1
> This patch unlocks the ability to run release-libraries on push events to main,
> which is a way less error-prone approach than publishing directly on PR create.
Let's update charming-actions to the latest 2.2.2 which looks stable for other repos.
> Bump charming-actions to 2.2.2 (to fix release-libraries@2.2.0)

- lib/charms/data_platform_libs/v0/data_interfaces.py
- tests/unit/test_data_interfaces.py
> [ISSUE-42;ISSUE-43] is_resource_created improvements and fixes

- .github/workflows/ci.yaml
- tox.ini
Update components to the latest versions in Juju 2.9 LTS.
The old pinning should no longer be necessary.
> Bump juju to 2.9.38, libjuju to 2.9.38.1 and remove flake8 pinning

- lib/charms/data_platform_libs/v0/data_interfaces.py
- tests/integration/kafka-charm/metadata.yaml
- tests/integration/kafka-charm/src/charm.py
- tests/unit/test_data_interfaces.py
It is a typo spotted by new codespell and affect other repos, like https://github.com/canonical/kafka-bundle/actions/runs/4373173395/jobs/7651007585
> Fix typo Kakfa -> Kafka

- lib/charms/data_platform_libs/v0/data_interfaces.py
This PR addresses the differences between the endpoints in VM charms and Kubernetes charms in respective docstrings.
Thank you :)
> docs: add endpoint description on vm/k8s charms

- lib/charms/data_platform_libs/v0/data_interfaces.py
- tests/integration/application-charm/actions.yaml
- tests/integration/application-charm/charmcraft.yaml
- tests/integration/application-charm/src/charm.py
- tests/integration/test_charm.py
- tests/unit/test_data_interfaces.py
- tox.ini
Jira ticket: [DPE-1373](https://warthogs.atlassian.net/browse/DPE-1373)
As an juju admin, I should be able to run:
* `juju relate postgresql-k8s:postgresql_client TODO_charmname:postgresql_client`
* New relation requests do not contain extensions information but “data_interfaces” library which implements new relation should have “is_postgresql_plugin_enabled” function. This function returns True or False depending if the extension is installed and configured.
* (with new relation) the application charm expects to set blocked status to forcing users to enable extension manually through config options (https://github.com/canonical/postgresql-operator/pull/139).
Created the new method and add a local import to psycopg to avoid requiring that application charms not using the new method need …
> Add is_postgresql_plugin_enabled method

- metadata.yaml
The incorrect option name used here historically, see commit 36a7a848b892ec46a982f290fee9ca519876d75e.
Specification: https://discourse.charmhub.io/t/file-metadata-yaml/5213#heading--display-name
> DPE-1180 Fix display name: s/display_name/display-name/ + add docs

- .gitignore
- lib/charms/data_platform_libs/v0/data_interfaces.py
- tests/unit/test_data_interfaces.py
Adds basic validation to avoid topic wildcards on Kafka.
> [DPE-1928] Validate wildcard topic on KafkaRequires

- lib/charms/data_platform_libs/v0/upgrade.py
- pyproject.toml
- tests/unit/test_upgrade.py
- `build_complete_sem_ver()` converts string versions into full major.minor.patch semantic versions, padding with 0s where not specified
- etc `1.3` --> `[1, 3, 0]`
- All verification functions called in `verify_inequality_requirements` wrapper, returning boolean if passed arg version meets passed arg requirement
- Involved functions support version definition specification used by [`poetry`](https://python-poetry.org/docs/dependency-specification/), supporting:
- [Caret](https://python-poetry.org/docs/dependency-specification/#caret-requirements)
- [Tilde](https://python-poetry.org/docs/dependency-specification/#tilde-requirements)
- [Wildcard](https://python-poetry.org/docs/dependency-specification/#wildcard-requirements)
- [Inequality](https://python-poetry.org/docs/dependency-specifica …
> chore: core structure of base DataUpgrade lib and handlers for pre upgrade-charm

- lib/charms/data_platform_libs/v0/upgrade.py
- `[]` and `None` are both falsey in Python. When the final unit had been popped from the list, we would attempt to set that empty list to relation data by referencing the property. The property checks for `if not X: fetch`, getting the un-popped value from the relation data
- When we recursed on the leader, we'd get recursion limit errors, as it would never exit due to it just re-setting the original stack
- Fixed by specifically checking for `if self._upgrade_stack is None`
- When unset, we'd handle relation events before upgrades had progressed
- Fixed, now we can check for `idle` and exit
> fix: various bugs

- lib/charms/data_platform_libs/v0/s3.py
from bug report https://github.com/canonical/postgresql-operator/issues/180 by @kian99 
> Hey folks, a relation problem. I've deployed Postgresql from 14/stable. I related it to another charm "s3-integrator" that provides it with config for communicating with an S3 bucket. I then removed the relation with --force and went through the process of adding and removing the relation a few times as I worked on some firewall issues.
> 
> Now i'm facing an issue where Postrgres thinks the s3-integrator charm is still related (see below) and further operations are failing because of some checks in the charm expecting only a single relation. 
> $ juju exec --unit postgresql/0 -- relation-ids s3-parameters
> s3-parameters:13
> s3-parameters:14
> DPE-2218 Better handling of broken s3 relation

- lib/charms/data_platform_libs/v0/data_interfaces.py
Using Juju 3.2.0 and data_interfaces 0.15, if the developer tries to access the relation data early in the charm's life (i.e. in the constructor), then in some cases, a ModelError is thrown and not yet caught.
This occurs most obviously when scaling an application - the peer relation joined hook fires very early in the new unit's life, and if _is_relation_active is called at this point, a ModelError can be thrown.
fixes https://pastebin.canonical.com/p/zKJPQ8B3gy/
> fix ModelError exception

- .gitignore
- lib/charms/data_platform_libs/v0/upgrade.py
- tests/unit/test_upgrade.py
bulk of changes are related to pulling already merged k8s support (PR #77)
* `on_upgrade_charm` calls for `self._upgrade_supported_check()` for differing conditions for k8s and vm, setting `state` and statuses accordingly
> adapt for k8s statuses

- .gitignore
- lib/charms/data_platform_libs/v0/upgrade.py
- tests/unit/test_upgrade.py
- Units now stay in the same state they were before failing, not also failing
- Running `pre-upgrade-check` action after a cluster has failed sets `state=recovering` to the leader
- `upgrade-charm` modifies upgrade-stack to insert any units that were already popped + completed (i.e not the failed ones)
- Failed units are inserted to the top of the existing stack 
- `upgrade-granted` now only emitted when all units are ready
- `BlockedStatus` with optional `cause` passed by `set_unit_failed()` if unit fails during
- `BlockedStatus` with generic message if any other unit failed during
- `MaintenanceStatus` throughout
- `ActiveStatus` when setting back to `state=idle`
> DPE-2288 - feat: support rollbacks, add statuses

- lib/charms/data_platform_libs/v0/upgrade.py
> Removed unnedeed defer

- lib/charms/data_platform_libs/v0/data_interfaces.py
- tests/unit/test_data_interfaces.py
When a relation alias is provided it should be set not only on the unit relation data level, but also on the application relation data level
> [DPE-2746] Set relation alias also on application data level

- lib/charms/data_platform_libs/v0/upgrade.py
Upgrade lib throws an exception on focal series charms: `TypeError: 'type' object is not subscriptable`
Use Dict annotation
> [DPE-1770] Focal compatibility for upgrade lib

- .github/workflows/ci.yaml
- lib/charms/data_platform_libs/v0/data_interfaces.py
- tests/integration/application-charm/actions.yaml
- tests/integration/application-charm/src/charm.py
- tests/integration/database-charm/actions.yaml
- tests/integration/database-charm/src/charm.py
- tests/integration/helpers.py
- tests/integration/test_charm.py
- tests/unit/test_data_interfaces.py
Adding `delete_relation_data()` function that allows to remove fields from the relation on request.
IT's NOT implemented as part of the update function, given the already existing complexity.
I.e. as we're already "cherry-picking" among input fields ("Is this in a secret?" "Is this in the databag?") we shouldn't further load this logic to even select whether `None` values may be supplied to indicate removal for real.... Ah, and don't forget to remove the secret if all fields deleted -- otherwise you get an error if saving an empty secret... 
Pls, no more spagetti than what we already have :-)
Instead it seems to make more sense to have a clean interface for deletion. If one wants to delete a field, (s)he should do that explicitly. Cleaner interface, cleaner code...
> [DPE-2828] Delete field from relation

- .github/workflows/ci.yaml
- lib/charms/data_platform_libs/v0/data_interfaces.py
- tests/integration/application-charm/actions.yaml
- tests/integration/application-charm/src/charm.py
- tests/integration/data/data_interfaces.py
- tests/integration/database-charm/actions.yaml
- tests/integration/database-charm/src/charm.py
- tests/integration/test_charm.py
- tests/integration/test_rolling_upgrade.py
- tox.ini
A major bug was discovered. When using secrets, all secret info was also duplicated into the databag.
On [line 783](https://github.com/canonical/data-platform-libs/blob/main/lib/charms/data_platform_libs/v0/data_interfaces.py#L783) the `second_chance_as_normal_field` variable was always true. (Should have been set `False` in modification functions, by mistake.)
However since in parallel we had concerns regarding rolling upgrades, I provided a fix that also addresses the rolling upgrades issue.
During development [another bug](https://github.com/canonical/data-platform-libs/issues/108) was discovered. To be fixed in a separate PR. Tests `xfail`-ing until.
> [DPE-2850][FIX] Secret content duplication AND rolling update safe

- lib/charms/data_platform_libs/v0/data_interfaces.py
- tests/integration/test_charm.py
Version 23
- Fixing exceptions raised by deleting non-existing fields
- NOTE: partially internal garbage, thus we only add a `debug()` message on it,
- Issue https://github.com/canonical/data-platform-libs/issues/110 opened , later priority
- Problem revealed by @carlcsaposs-canonical testing MySQL Router: https://github.com/canonical/mysql-router-k8s-operator/pull/152#issuecomment-1787194530
- Fixing exceptions on `get_relation() when `relation.app` is not there
- Reason: local databag still has to be available
- Problem revealed by @carlcsaposs-canonical testing MySQL Router: https://github.com/canonical/mysql-router-k8s-operator/pull/152#issuecomment-1786997913
> [DPE-2876] Fix on fetching local databag (when relation is broken)

- lib/charms/data_platform_libs/v0/data_interfaces.py
- tests/integration/conftest.py
- tests/integration/helpers.py
- tests/integration/test_charm.py
- [Lib tries to access app databag from non-leader unit · Issue #111 · canonical/data-platform-libs](https://github.com/canonical/data-platform-libs/issues/111) 
- [Updated secret still at earlier content in observers (that labelled them) · Issue #108 · canonical/data-platform-libs](https://github.com/canonical/data-platform-libs/issues/108)  HIGH IMPORTANCE !!!!!!!!!!!!!!!!!!
> [DPE-2882] Addressing issues 108 and 111

- lib/charms/data_platform_libs/v0/data_interfaces.py
- tests/integration/database-charm/actions.yaml
- tests/integration/database-charm/metadata.yaml
- tests/integration/database-charm/src/charm.py
- tests/integration/helpers.py
- tests/integration/test_charm.py
- tests/integration/test_rolling_upgrade.py
- tests/unit/test_data_interfaces.py
- tox.ini
Implementing Peer Relations data abstraction and data interaction as the exact same like what we have for Cross-charm relations.
The proposal is FULLY re-using already existing code (behavior) set for Cross-charm Relations.
There are 3 Peer-specific requirements (how it's been implemented in the charms) that are taken over here:
Rolling upgrades
1. If only databag was used (i.e. Internal Secrets in plain text) -> We move secrets one-by-one to a Juju Secret whenever the secret field is referred to
2. If the charm was already using secrets BUT not by labels but URI ->  We remove the URI from the databag and stick a label on the secret
Protection against old bugs (i.e. versions compatibilty):
3. "deleted label": Soft delete, i.e. if a secret is to be removed, we just replace the value with a …
> [DPE-3054] PeerRelation withing the same guidelines as Requires and Provides

- lib/charms/data_platform_libs/v0/data_interfaces.py
- lib/charms/data_platform_libs/v0/data_secrets.py
- tests/conftest.py
- tests/integration/application-charm/src/charm.py
- tests/integration/secrets-charm/lib/charms/data_platform_libs/v0/data_secrets.py
- tests/integration/test_charm.py
- tests/unit/test_data_interfaces.py
Adds an expose flag to the DatabaseRequires, to be consumed by subordinate router charms, so that they can know when to serve locally and when to expose the service (data-integrator).
> [DPE-3450] Add expose field to requires relation

- lib/charms/data_platform_libs/v0/data_interfaces.py
- tests/unit/test_data_interfaces.py
Fully compatible with Charm Patters Design: https://github.com/canonical/zookeeper-operator/pull/121
(Backwards compatibility is confirmed by pipelines here.)
This PR implements the structure below. Allowing both for an internal separation of concerns (Data Abstraction vs. Event Handling), both for a smooth usage with [Data Interfaces Charm Patterns](https://docs.google.com/document/d/1TojdN0BN3qQ1fQ_uyMd7pCL6L5NNXtFo6DrOUwU5uFI/edit?usp=sharing) while keeping the old interface fully intact.
> [DESIGN] Separation of Concerns (Data Abstraction vs. Event Handlers)

- lib/charms/data_platform_libs/v0/data_interfaces.py
- tests/integration/database-charm/actions.yaml
- tests/integration/database-charm/src/charm.py
- tests/integration/test_charm.py
- tests/unit/test_data_interfaces.py
There was a major copy-paste mistake on the new `DataPeerOtherUnit` class (that will be required typically for [this functionality](https://github.com/canonical/zookeeper-operator/blob/c71086ffe0cfb877c5aa11b99765cc6e87d26db9/src/core/cluster.py#L59-L70) demonstarted in Zookeeper).
> [DPE-3876][BUGFIX] DataPeerOtherUnit

- lib/charms/data_platform_libs/v0/data_interfaces.py
- tests/unit/test_data_interfaces.py
This PR is the "continuation" of [earlier POC](https://github.com/canonical/data-platform-libs/pull/143).
See how it works on ZooKeeper: https://github.com/canonical/zookeeper-operator/pull/122
> [DPE-3874] `dict` representation for Data (i.e. "back to databag" :-) )

- lib/charms/data_platform_libs/v0/data_interfaces.py
Once again I had to remember the hard way: `data_interfaces` MUST be strongly backwards compatible.
Both in terms of code and in terms of Python versions, etc.
Adding generics to the `dict` implementation parent class broke Python 3.9> compatibility.
The proposed fix executes correctly on earlier Python versions as well: https://github.com/canonical/data-platform-libs/actions/runs/8559046518
> [DPE-3906][BUGFIX] dict implementation not supporting Python 3.9> (issue #152)

- lib/charms/data_platform_libs/v0/data_interfaces.py
I have noticed that we have some spelling checks that do not follow the convention we have for databases.
> [MISC] Fix Kafka spelling

- lib/charms/data_platform_libs/v0/data_interfaces.py
Copying from a comment:
Passing `self` to `getattr` means that none of those fields on the array exist on the inheritance tree from `KafkaRequiresEventHandlers`. Because of this, the lib would always write an empty string to databag, so `topic_requested` is never triggered.
Using the full `KafkaRequires` class works because we pass data indirectly to via `KafkaRequiresEventHandlers.__init__(self, charm, self)` The 3rd argument is a self reference, so `KafkaRequiresData` fields are available down the line.
NOTE: alternative, less intrusive fix
```python
relation_data = {
f: getattr(self.relation_data, f.replace("-", "_"), "")
for f in ["consumer-group-prefix", "extra-user-roles", "topic"]
}
```
> Fix relation data access

- .github/workflows/ci.yaml
- lib/charms/data_platform_libs/v0/data_interfaces.py
- tests/__init__.py
- tests/integration/conftest.py
- tests/integration/database-charm/actions.yaml
- tests/integration/database-charm/src/charm.py
- tests/integration/test_rolling_upgrade_from_specific_version.py
- tests/unit/test_data_interfaces.py
- tests/unit/test_data_models.py
- tests/unit/test_upgrade.py
- tox.ini
Bug reported in Jira ticket https://warthogs.atlassian.net/browse/DPE-4416
The root cause was identified as an issue within the logic implemented for rolling upgades. In particular on an occasion where the (peer) secret label may change (as it happened in v34).
Since Juju is not supporting label changes, whenever we need to change a label for a secret, we need to create a new secret (using the previous content) and associate this new secret with the new label.
(The underlying logic is more complicated than it sounds, as we need to maintain backwards compatibility as well, until the first write operation.)
This logic had a bug, revealing on this particular use case:
- charm upgrade from libs < v34 to libs > v34
- peer secret changes
- peer secret changes for a second time, _within_ the …
> [DPE-4416] URI exists while re-creating secret with modified label

- .github/workflows/ci.yaml
- CONTRIBUTING.md
- charmcraft.yaml
- tests/conftest.py
- tests/integration/application-charm/charmcraft.yaml
- tests/integration/application-s3-charm/charmcraft.yaml
- tests/integration/conftest.py
- tests/integration/database-charm/charmcraft.yaml
- tests/integration/database-charm/src/charm.py
- tests/integration/dummy-database-charm/charmcraft.yaml
- tests/integration/dummy-database-charm/lib/charms/data_platform_libs/v0/data_interfaces.py
- tests/integration/dummy-database-charm/src/charm.py
- tests/integration/s3-charm/charmcraft.yaml
- tests/integration/test_charm.py
- tests/integration/test_rolling_upgrade.py
- tests/integration/test_rolling_upgrade_from_specific_version.py
- tests/integration/test_s3_charm.py
- tests/unit/test_data_interfaces.py
- tox.ini
The libs [are supporting](https://chat.canonical.com/canonical/pl/isjm3to6dtrsdpe1pduuk56wpr) two Ubuntu versions
- focal
- jammy
Together with a number of Juju versions
- 2.9/stable
- 3.1/stable
- 3.2/stable
- 3.3/stable
- 3.4/stable
- 3.5/stable
The pipelines should be reflecting that ;-)
See the documentation added in the CONTRIBUTING document regarding the cross-OS testing.
Note: We are actually using the same mechanism as `mysql-router-operator`. We should be moving to the new re-usable 
workflows when together with that charm -- once the parametrization required may be supported.
> [DPE-4530] CI testing both forward (Juju) and backwards (focal)

- lib/charms/data_platform_libs/v0/upgrade.py
- pyproject.toml
- tox.ini
Planned units are not correct for subordinate charms [juju bug](https://bugs.launchpad.net/juju/+bug/2025676), so upgrade will not start on a single unit subordinate charm.
> [MISC] Don't use planned units for single unit cluster upgrade

- lib/charms/data_platform_libs/v0/data_interfaces.py
Scaling up subordinate charms with a single endpoint is error prone by default, since the endpoint is local, but a new unit may not yet be ready to serve when the new consumer receives a `database_created` event. The PR adds a check to the unit relation databag for a `state` value that can be used to synchronise the emission of events and `subordinated` flag in the provider application databag. The change should be backwards compatible.
PR https://github.com/canonical/pgbouncer-operator/pull/274 implements the other side of the synchronisation.
> [DPE-4772] Subordinate scale up

- lib/charms/data_platform_libs/v0/data_interfaces.py
Publishing of the data_interfaces lib fails due to size limitations:
```
Store operation failed:
- None: Content too large (got 131339 bytes, limit is 131072 in utf8)
```
Deleting some logs and comments to push below the limit
> [MISC] Reduce the size of the library

- .github/workflows/ci.yaml
- lib/charms/data_platform_libs/v0/data_interfaces.py
- tests/integration/conftest.py
This PR is part of a sequence of seamless modifications impacting the libs internals.
The objective is to make the code better organized, extendable, maintainable (as currently it's getting out of hands).
- Within this scope a main area is compatibility and migration functionalities ensuring smooth Rolling Upgrades.
(We would like to have a better established structure/mechanism for related code. Current changes are a 1st stage pointing towards that direction, but are not yet the final solution.)
- Verbosity on the internal logic was much increased (~70-80 lines of changes are impacting docstrings or comments)
> [DPE-4531] data interfaces cleanup verbose minor refact

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
We see a lot of warnings in [CI test runs](https://github.com/canonical/data-platform-libs/actions/runs/9540460074) to upgrade to `actions/checkout@v4` due to Node 16 deprecation warnings
Upgrade to use v4
> Upgrade to use actions/checkout@v4 to avoid Node 16 warnings in CI runs

- lib/charms/data_platform_libs/v0/data_interfaces.py
- tests/integration/conftest.py
- tests/unit/test_data_interfaces.py
https://github.com/canonical/data-platform-libs/issues/193
In case any write operation may take place before the protocol is established the `Provider` may not yet be aware whether secrets are to be used or not. Thus, the write operation may end up as plain text in the databag, instead of secrets.
Example:
A charm may receive TLS certs anytime, that are to be shared on a client relation.
When the charm got the TLS secrest, it just "blindly" writes them using `update_relation_data()` on `update-status` or `certificate-available` or so.
Which technically could be executed BEFORE the  `Requirer` (!!!!) `relation-created` handler would put the `requested-secrets` list -- highlighting that TLS certs are stored as a Juju Secret on this relation.
No `Provider` write operation is allowed before …
> [DPE-5306][SECURITY] No write before protocol init

- .github/workflows/ci.yaml
- tests/unit/test_data_secrets.py
* Fix unit test failures e.g. [here](https://github.com/canonical/data-platform-libs/actions/runs/12759167499/job/35562470069#step:4:559)
* Add juju 3.6 to the integration test matrix
> [MISC] Fix unit tests and add juju 3.6 test runs

- .github/workflows/release.yaml
Charm release fails due to enabled destructive mode and trying to build 22.04 charm on 24.04
The failure on release is https://github.com/canonical/data-platform-libs/actions/runs/13115477658/job/36589968827#step:5:16
> [MISC] Disable destructive mode

- lib/charms/data_platform_libs/v0/data_interfaces.py
- tests/unit/test_data_interfaces.py
Add a `read-only-uri` secret field. Implements DA158.
> [DPE-6555] Add read only URIs

- lib/charms/data_platform_libs/v0/data_interfaces.py
- tests/unit/test_data_interfaces.py
This pull request includes several changes to the `lib/charms/data_platform_libs/v0/data_interfaces.py` file, focusing on renaming variables for clarity and updating secret fields handling. The most important changes include renaming `_secret_fields` to `_local_secret_fields`, updating the handling of provided and requested secrets, and modifying the secret group mapping.
* Renamed `_secret_fields` to `_local_secret_fields` throughout the file for better clarity and consistency. [[1]](diffhunk://#diff-7bc59790c534f66e8e6a800e826efade12b1320cfe3b37b4fdc9a41ca0b0a6dfL986-L989) [[2]](diffhunk://#diff-7bc59790c534f66e8e6a800e826efade12b1320cfe3b37b4fdc9a41ca0b0a6dfL1013-R1014) [[3]](diffhunk://#diff-7bc59790c534f66e8e6a800e826efade12b1320cfe3b37b4fdc9a41ca0b0a6dfL1718-L1720) …
> [DPE-6457]: Implement feedback from etcd interface implementation

- lib/charms/data_platform_libs/v0/data_interfaces.py
`fetch_relation_data` will not return any values on non-leader units due to an overprotective check.
> [MISC] Empty fetch_relation_data on follower units

- lib/charms/data_platform_libs/v1/data_models.py
This PR fixes the `LIBPATCH` stated in the recently merged Data-models v1 [PR](https://github.com/canonical/data-platform-libs/pull/201), to unblock its publication.
---
Adding reviewers according to this Cross-team components maintainers [page](https://canonical-data.readthedocs-hosted.com/products/cross-team/).
> [MISC] Fix data-models v1 LIBPATCH

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
Replace `charming-actions/release-libraries` with noctua tool from the observability team.
> [MISC] Noctua lib publish

- lib/charms/data_platform_libs/v0/data_interfaces.py
- tests/v0/integration/application-charm/actions.yaml
- tests/v0/integration/application-charm/src/charm.py
- tests/v0/integration/kafka-charm/src/charm.py
- tests/v0/integration/test_kafka_charm.py
This PR adds `mtls-cert` field to `kafka_client` relations, compliant with DA150. This change is backwards-compatible since the field is optional and it also doesn't break clients which rely on positional args.
> [DPE-7365] feat: add mtls-cert to kafka_client

- lib/charms/data_platform_libs/v0/database_provides.py
- lib/charms/data_platform_libs/v0/database_requires.py
- lib/charms/data_platform_libs/v0/s3.py
- lib/charms/data_platform_libs/v0/upgrade.py
This PR fixes an issue caused by [this PR](https://github.com/canonical/data-platform-libs/pull/134/files#diff-a01d43dd46de468e0afbd31ac8efced74720d6cbaf7c62c6f68b71d0066aef6c), which didn't update the LIBPATCH on some libs, causing the whole release CI to abort in the new `noctua`-based workflow
https://github.com/canonical/data-platform-libs/actions/runs/15726984751/job/44333862654
> fix: bump changed libs LIBPATCH

- lib/charms/data_platform_libs/v0/s3.py
Charmcraft fetch-lib claims everything except data_interfaces (which should bee released) is up to date:
```
Library charms.data_platform_libs.v0.data_interfaces has local changes, cannot be updated.
Library charms.data_platform_libs.v0.data_models was already up to date in version 0.5
Library charms.data_platform_libs.v0.data_secrets was already up to date in version 0.3.
Library charms.data_platform_libs.v0.database_provides was already up to date in version 0.5.
Library charms.data_platform_libs.v0.database_requires was already up to date in version 0.7.
Library charms.data_platform_libs.v0.s3 was already up to date in version 0.5.
Library charms.data_platform_libs.v0.upgrade was already up to date in version 0.19.
Library charms.data_platform_libs.v1.data_models was already up to date …
```
> [MISC] Revert s3 libpatch

- lib/charms/data_platform_libs/v0/data_interfaces.py
This PR aims at fixing the error occurring [here](https://github.com/canonical/opensearch-operator/actions/runs/15680439683/job/44170961194?pr=655#step:8:20795) - for opensearch:
```
File "/var/lib/juju/agents/unit-opensearch-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 1673, in _on_secret_changed_event
raise NotImplementedError
```
> Fix missing impl. of _on_secrets_changed abstract method

- requirements/v0/requirements.txt
- tox.ini
Apparently, they switched to `uv` for builds in `pytest-operator` [v0.43](https://github.com/charmed-kubernetes/pytest-operator/pull/148/files#diff-84321598744d84dbee2318e634c74c9aae39a1c253f1c4bd17ebf9ef2f807b11) and that has broken things in our CI.
This PR pins `ops` to `<3` and `pytest-operator` to `<0.43`
> chore: pin ops to <3 and pytest-operator to <0.43
